### ISSUE TITLE
Re-create frontend in React

### ISSUE THREAD

**Issue by afaneca** [afaneca/myfin#374]
I'm taking this opportunity to rebuild the web frontend from the ground up, combining React and TypeScript to create a (hopefully) more coherent UI/UX and a maintainable codebase.

Steps:

- [x] Routing
- [x] Login & Auth/Session
- [x] Register/Account creation
- [x] Dashboard
- [x] Transactions
  - [x] List transactions 
  - [x] Create transaction
  - [x] Edit transaction
  - [x] Auto-categorize transaction
  - [x] Split transaction
  - [x] Remove transaction 
  - [x] Cache last transaction in add form
  - [x] Import transactions
- [x] Accounts
  - [x] List accounts
  - [x] Create accounts
  - [x] Edit accounts
  - [x] Remove accounts
- [x] Categories
  - [x] List categories
  - [x] Create categories
  - [x] Edit categories
  - [x] Remove categories 
- [x] Entities
  - [x] List entities
  - [x] Create entities
  - [x] Edit entities
  - [x] Remove entities 
- [x] Tags
  - [x] List tags
  - [x] Create tags
  - [x] Edit tags
  - [x] Remove tags
- [x] Rules
  - [x] List rules
  - [x] Create rules
  - [x] Edit rules
  - [x] Remove rules
- [x] Budgets
  - [x] List budgets
  - [x] Create budgets
  - [x] Budgets details
  - [x] Remove details
- [x] Stats
  - [x] Patrimony evolution
  - [x] Projections
  - [x] Expenses
  - [x] Income
  - [x] Year-by-Year
- [x] Investments
   - [x] Summary
   - [x] Assets
     - [x] List asset
     - [x] Create asset
     - [x] Edit asset
     - [x] Edit asset value
     - [x] Remove asset 
   - [x] Transactions
     - [x] List transactions
     - [x] Create transactions
     - [x] Edit transactions
     - [x] Remove transactions 
   - [x] Reports 
- [x]  Profile
- [x] Final UI tweaks

**Comment by damianphim** [comment]
Hello!

Do you want some help moving this to React? If so, just give me some tasks and I'll get started.

Let me know :)

**Comment by afaneca** [comment]
> Hello!
> 
> Do you want some help moving this to React? If so, just give me some tasks and I'll get started.
> 
> Let me know :)

Hi, thanks for your interest in the project!
I'm not actively looking for code contributions at this point, since I'm still experimenting quite a bit with the react code and so the structure is not quite there yet in terms of maturity and consistency.

However, if you'd still like to contribute, you're welcome to being laying the ground work on the "Stats" screens, since I'll be focusing my attention on other areas of the frontend for the next few weeks. If, instead, you'd prefer to work on some other UI/UX optimization, feel free to pitch in. I'll gladly review your PRs :)
